#!/bin/sh

configure_zsh() {
    # Stop if zsh is not present
    if [ ! -x /usr/bin/zsh ]; then
	return
    fi
    # Stop if user has opted out of zsh
    if echo "${LIVE_CONFIG_CMDLINE}" | grep -qs 'nozsh'; then
	return
    fi
    chsh --shell /usr/bin/zsh threat
    chsh --shell /usr/bin/zsh root
}

configure_usergroups() {
    # Ensure those groups exist
    addgroup --system kaboxer || true
    addgroup --system wireshark || true

    # adm - read access to log files
    # dialout - for serial port access
    # kaboxer - for kaboxer
    # vboxsf - shared folders for virtualbox guest
    # wireshark - capture sessions without being root
    threat_groups="adm dialout kaboxer vboxsf wireshark"

    for grp in $threat_groups; do
	getent group $grp >/dev/null || continue
	usermod -a -G $grp threat
    done
}

# Avoid configuring multiple times in case persistence is enabled
if [ -e /var/lib/live/config/threat-user-setup ]; then
    exit 0
fi

# Set "threat" as password for the user threat
usermod -p 'AqLUsDitNnTsw' threat

# Change default shell to zsh
configure_zsh

# Add threat user to additional groups
configure_usergroups

# Remember that this script has been run
touch /var/lib/live/config/threat-user-setup
